language: sh

sudo: required

branches:
  only:
    - master
    - devel
    
services:
  - docker

env:
  global:
    - secure: "slXmqyKKIQ0eA21iLjptTCdlBaSMtjl2E/Gg+PVgHfc7DZ/O0LFCxV+IzSdnsYXsjhp9e8NN866/CVSHaT/DeLXfBQNHt7m0zp0Y1rnsGUvpG57Qp7czSI5JZw0Xy4sdXDw4YOyRsDspVGL23LNukTiHKEq8my5QjYFCBLycVCi7iXC4dGNOwY/PY8wFaDE1NwkH8ZtCD85jqKZhavYrGabDHpGbTaQNgkjwRSujGJG1tIi+pCsj3txWJxOPktwoL9zMOHC80GKb3UaDk3s0OorCMCQc0CW1cmetJUutvzd4fB3Zf6XQ4RForLi1V+hExObNHBrhB5U/Ot68eWVYoW9tFWOE99HTMzlsHp2RAiq2pxHj39TIJZF7ndZLa2ig/ms9Q2kRSSKQiLH41HV1yDmVDshDtw/9TRHGvnBuTAomL6CDH7/WKXsP1pMmEE6BhNpRbajm8Xb+P08bcpFlrHi1YRLPNv2Z5MF974Hc8jsYY3DX+co2DqMHz6sLIcmdYswAhIu5cgprLeomTlWraVkGjSBvVklMKF7H3KGMa64Jv6jljBgQIyc2fjmQLSiEyUqT7RkaJmz3DPEPekvbEEfJyxqlu2Is9hqSb//oYsiZdYSTIfbxU+3fZh5MSfPdooG3+w7x4LdFqjqP84XoDN/OymE8kRlkfxErS6hXJZY="    

before_install:
  - docker pull cmbant/cosmobox

install:
  - chmod +x tests/run_tests.sh
  - mkdir testfiles
      
script:
  - docker run -v $(pwd):/camb -e TRAVIS_BRANCH -e CAMB_TESTS_NO_SOURCES=1 -e CAMB_TESTS_NO_DE=1 -t cmbant/cosmobox /bin/bash -c "/camb/tests/run_tests.sh"

after_script:
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_REPO_SLUG == "cmbant/CAMB" && bash tests/upload_tests.sh
